<a href="https://colab.research.google.com/github/Shubham21122002/Python/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# 1. Create a constant tensor
const_tensor = tf.constant([1, 2, 3])
print("Constant Tensor:", const_tensor)

# 2. Create a tensor with zeros
zero_tensor = tf.zeros([3, 3])
print("Zero Tensor:\n", zero_tensor)

# 3. Create a tensor with ones
ones_tensor = tf.ones([2, 2])
print("Ones Tensor:\n", ones_tensor)

# 4. Create a random tensor
random_tensor = tf.random.uniform([2, 2])
print("Random Tensor:\n", random_tensor)

# 5. Add two tensors
sum_tensor = tf.add(const_tensor, const_tensor)
print("Sum of Tensors:", sum_tensor)

# 6. Multiply two tensors
product_tensor = tf.multiply(const_tensor, 2)
print("Product of Tensor:", product_tensor)

# 7. Matrix multiplication
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])
matmul_tensor = tf.matmul(matrix1, matrix2)
print("Matrix Multiplication:\n", matmul_tensor)

# 8. Reshape a tensor
reshaped_tensor = tf.reshape(const_tensor, [3, 1])
print("Reshaped Tensor:\n", reshaped_tensor)

# 9. Cast tensor type
float_tensor = tf.cast(const_tensor, tf.float32)
print("Float Tensor:", float_tensor)

# 10. Calculate the mean of a tensor
mean_tensor = tf.reduce_mean(matrix1)
print("Mean of Tensor:", mean_tensor)

# 11. Calculate the sum of a tensor
sum_all_tensor = tf.reduce_sum(matrix1)
print("Sum of All Elements in Tensor:", sum_all_tensor)

# 12. Calculate the max of a tensor
max_tensor = tf.reduce_max(matrix1)
print("Max Element in Tensor:", max_tensor)

# 13. Calculate the min of a tensor
min_tensor = tf.reduce_min(matrix1)
print("Min Element in Tensor:", min_tensor)

# 14. Find the argmax (index of max) of a tensor
argmax_tensor = tf.argmax(matrix1)
print("Argmax of Tensor:", argmax_tensor)

# 15. Find the argmin (index of min) of a tensor
argmin_tensor = tf.argmin(matrix1)
print("Argmin of Tensor:", argmin_tensor)

# 16. Create a variable tensor
variable_tensor = tf.Variable([1.0, 2.0, 3.0])
print("Variable Tensor:", variable_tensor)

# 17. Update a variable tensor
variable_tensor.assign([4.0, 5.0, 6.0])
print("Updated Variable Tensor:", variable_tensor)

# 18. Gradient calculation
with tf.GradientTape() as tape:
    tape.watch(variable_tensor)
    loss = tf.reduce_sum(variable_tensor ** 2)
grad = tape.gradient(loss, variable_tensor)
print("Gradient:", grad)

# 19. Transpose a tensor
transposed_tensor = tf.transpose(matrix1)
print("Transposed Tensor:\n", transposed_tensor)

# 20. Tile a tensor (repeat elements)
tiled_tensor = tf.tile(const_tensor, [2])
print("Tiled Tensor:", tiled_tensor)

# 21. Concatenate two tensors
concat_tensor = tf.concat([const_tensor, const_tensor], axis=0)
print("Concatenated Tensor:", concat_tensor)

# 22. Calculate the shape of a tensor
shape_of_tensor = tf.shape(matrix1)
print("Shape of Tensor:", shape_of_tensor)

# 23. Create an identity matrix
identity_tensor = tf.eye(3)
print("Identity Matrix:\n", identity_tensor)

# 24. Generate a sequence of numbers
sequence_tensor = tf.range(1, 10, 2)
print("Sequence Tensor:", sequence_tensor)

# 25. Convert numpy array to tensor
import numpy as np
numpy_array = np.array([5, 6, 7])
numpy_tensor = tf.convert_to_tensor(numpy_array)
print("Numpy to Tensor:", numpy_tensor)


Constant Tensor: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Zero Tensor:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
Ones Tensor:
 tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
Random Tensor:
 tf.Tensor(
[[0.06257021 0.52701986]
 [0.05428731 0.8583286 ]], shape=(2, 2), dtype=float32)
Sum of Tensors: tf.Tensor([2 4 6], shape=(3,), dtype=int32)
Product of Tensor: tf.Tensor([2 4 6], shape=(3,), dtype=int32)
Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Reshaped Tensor:
 tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
Float Tensor: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Mean of Tensor: tf.Tensor(2, shape=(), dtype=int32)
Sum of All Elements in Tensor: tf.Tensor(10, shape=(), dtype=int32)
Max Element in Tensor: tf.Tensor(4, shape=(), dtype=int32)
Min Element in Tensor: tf.Tensor(1, shape=(), dtype=int32)
Argmax of Tensor: tf.Tensor([1 1], shape=(2,), dtype=int64)
Argmin of Tensor: tf.Tenso